import type {
  ProgrammingChallenge,
  ProgrammingDifficulty,
  ProgrammingExamBoard,
  ProgrammingMode,
  ProgrammingQualification,
} from "@/types/programming";

export const programmingChallenges: ProgrammingChallenge[] = [
  {
    id: "gcse-f-output-total",
    title: "Output a Total",
    description: "Store two values, calculate their total and print it.",
    topicId: "variables-data-types",
    mode: "practice",
    difficulty: "foundation",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `first = 7
second = 5

# Calculate the total and print it.
`,
    visibleTests: [
      { id: "main", label: "Given values", input: "", expectedOutput: "12" },
    ],
    hiddenTests: [],
    hint: "Create a total using first + second, then pass it to print().",
    explanation:
      "A variable can store the result of an arithmetic expression. print() sends the result to standard output.",
    examinerTip:
      "Use the exact variable names supplied in a programming question unless alternatives are permitted.",
    xpReward: 40,
  },
  {
    id: "gcse-f-next-age",
    title: "Age Next Year",
    description: "Read an integer and output the value one year later.",
    topicId: "input-output-operators",
    mode: "practice",
    difficulty: "foundation",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `age = int(input())

# Output the person's age next year.
`,
    stdin: "15",
    visibleTests: [
      { id: "age-15", label: "Age 15", input: "15", expectedOutput: "16" },
    ],
    hiddenTests: [
      { id: "age-8", label: "Hidden age", input: "8", expectedOutput: "9", hidden: true },
      { id: "age-41", label: "Hidden age", input: "41", expectedOutput: "42", hidden: true },
    ],
    hint: "The input is already an integer. Add 1 and print the result.",
    explanation:
      "input() supplies text, int() converts it to an integer, and adding 1 calculates the next age.",
    examinerTip:
      "A common mistake is treating numeric input as text instead of converting it before arithmetic.",
    xpReward: 45,
  },
  {
    id: "gcse-f-pass-fail",
    title: "Pass or Fail",
    description: "Use selection to classify an examination mark.",
    topicId: "selection",
    mode: "practice",
    difficulty: "foundation",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `mark = int(input())

# Output Pass for marks of 40 or more.
# Otherwise output Fail.
`,
    stdin: "55",
    visibleTests: [
      { id: "pass", label: "Passing mark", input: "55", expectedOutput: "Pass" },
      { id: "boundary", label: "Boundary mark", input: "40", expectedOutput: "Pass" },
    ],
    hiddenTests: [
      { id: "fail", label: "Hidden failing mark", input: "39", expectedOutput: "Fail", hidden: true },
    ],
    hint: "Use if mark >= 40: followed by an else branch.",
    explanation:
      "Selection chooses a branch according to a Boolean condition. The boundary value 40 belongs in the Pass branch.",
    examinerTip:
      "Boundary values are frequently tested. Check whether the comparison should use > or >=.",
    xpReward: 55,
  },
  {
    id: "gcse-i-running-total",
    title: "Running Total",
    description: "Use iteration to calculate the total from 1 to n.",
    topicId: "iteration",
    mode: "practice",
    difficulty: "intermediate",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `n = int(input())
total = 0

# Add every integer from 1 to n to total.

print(total)
`,
    stdin: "5",
    visibleTests: [
      { id: "n5", label: "n = 5", input: "5", expectedOutput: "15" },
    ],
    hiddenTests: [
      { id: "n1", label: "Hidden minimum", input: "1", expectedOutput: "1", hidden: true },
      { id: "n10", label: "Hidden larger value", input: "10", expectedOutput: "55", hidden: true },
    ],
    hint: "range(1, n + 1) includes n.",
    explanation:
      "A running total starts at zero and adds each value during the loop. The upper bound of range() is exclusive.",
    examinerTip:
      "Off-by-one errors are common. Trace the first and last values generated by the loop.",
    xpReward: 70,
  },
  {
    id: "gcse-i-function-double",
    title: "Write a Function",
    description: "Complete a reusable function with a return value.",
    topicId: "procedures-functions",
    mode: "practice",
    difficulty: "intermediate",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `def double(number):
    # Return twice number.
    pass

value = int(input())
print(double(value))
`,
    stdin: "9",
    visibleTests: [
      { id: "nine", label: "double(9)", input: "9", expectedOutput: "18" },
    ],
    hiddenTests: [
      { id: "zero", label: "Hidden zero", input: "0", expectedOutput: "0", hidden: true },
      { id: "negative", label: "Hidden negative", input: "-4", expectedOutput: "-8", hidden: true },
    ],
    hint: "Use return number * 2 inside the function.",
    explanation:
      "A function receives a parameter and uses return to send a value back to the caller.",
    examinerTip:
      "Distinguish output from return: print() displays a value; return sends a value back from a function.",
    xpReward: 75,
  },
  {
    id: "gcse-h-count-vowels",
    title: "Count Vowels",
    description: "Combine strings, iteration and selection.",
    topicId: "arrays-strings",
    mode: "practice",
    difficulty: "higher",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `text = input().lower()
count = 0

# Count a, e, i, o and u in text.

print(count)
`,
    stdin: "computer science",
    visibleTests: [
      { id: "phrase", label: "computer science", input: "computer science", expectedOutput: "6" },
    ],
    hiddenTests: [
      { id: "none", label: "Hidden no-vowel string", input: "rhythms", expectedOutput: "0", hidden: true },
      { id: "mixed", label: "Hidden mixed case", input: "EdUcAtIoN", expectedOutput: "5", hidden: true },
    ],
    hint: `Inside the loop, test whether the current character is in "aeiou".`,
    explanation:
      "Each character is inspected once. Converting to lowercase avoids separate upper-case comparisons.",
    examinerTip:
      "For string algorithms, state clearly what each index or loop variable represents.",
    xpReward: 90,
  },
  {
    id: "gcse-debug-selection",
    title: "Repair the Selection",
    description: "Fix a syntax error and preserve the intended logic.",
    topicId: "debugging-errors",
    mode: "debug",
    difficulty: "foundation",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `temperature = int(input())

if temperature < 5
    print("Cold")
else:
    print("Not cold")
`,
    stdin: "3",
    visibleTests: [
      { id: "cold", label: "Cold value", input: "3", expectedOutput: "Cold" },
    ],
    hiddenTests: [
      { id: "warm", label: "Hidden warmer value", input: "8", expectedOutput: "Not cold", hidden: true },
    ],
    hint: "Python selection headers end with a colon.",
    explanation:
      "The program has a syntax error because the if statement is missing its colon.",
    examinerTip:
      "Classify errors precisely: syntax errors break language grammar; logic errors produce incorrect results.",
    xpReward: 50,
  },
  {
    id: "gcse-debug-loop",
    title: "Repair the Loop",
    description: "Fix an off-by-one logic error.",
    topicId: "debugging-errors",
    mode: "debug",
    difficulty: "intermediate",
    qualifications: ["GCSE"],
    examBoards: ["AQA", "OCR", "EDEXCEL"],
    starterCode: `n = int(input())
total = 0

for value in range(1, n):
    total += value

print(total)
`,
    stdin: "5",
    visibleTests: [
      { id: "n5", label: "n = 5", input: "5", expectedOutput: "15" },
    ],
    hiddenTests: [
      { id: "n3", label: "Hidden n = 3", input: "3", expectedOutput: "6", hidden: true },
    ],
    hint: "The end value passed to range() is excluded.",
    explanation:
      "range(1, n) stops at n - 1. The intended algorithm requires range(1, n + 1).",
    examinerTip:
      "A program can run without crashing and still contain a logic error.",
    xpReward: 70,
  },
  {
    id: "al-i-factorial",
    title: "Recursive Factorial",
    description: "Implement recursion with a correct base case.",
    topicId: "al-recursion",
    mode: "practice",
    difficulty: "intermediate",
    qualifications: ["A_LEVEL"],
    examBoards: ["AQA", "OCR"],
    starterCode: `def factorial(n):
    # Complete the recursive function.
    pass

value = int(input())
print(factorial(value))
`,
    stdin: "5",
    visibleTests: [
      { id: "five", label: "factorial(5)", input: "5", expectedOutput: "120" },
    ],
    hiddenTests: [
      { id: "zero", label: "Hidden base case", input: "0", expectedOutput: "1", hidden: true },
      { id: "one", label: "Hidden base case", input: "1", expectedOutput: "1", hidden: true },
    ],
    hint: "Return 1 for n <= 1; otherwise return n * factorial(n - 1).",
    explanation:
      "Each recursive call reduces the problem until the base case is reached, after which results unwind through the call stack.",
    examinerTip:
      "An A-level recursion explanation should identify both the base case and how each call moves toward it.",
    xpReward: 105,
  },
  {
    id: "al-h-oop",
    title: "Class and Method",
    description: "Implement a class with state and a method.",
    topicId: "al-oop",
    mode: "practice",
    difficulty: "higher",
    qualifications: ["A_LEVEL"],
    examBoards: ["AQA", "OCR"],
    starterCode: `class Rectangle:
    def __init__(self, width, height):
        # Store the two attributes.
        pass

    def area(self):
        # Return the area.
        pass

width = int(input())
height = int(input())
shape = Rectangle(width, height)
print(shape.area())
`,
    stdin: "7\n4",
    visibleTests: [
      { id: "seven-four", label: "7 by 4", input: "7\n4", expectedOutput: "28" },
    ],
    hiddenTests: [
      { id: "one-nine", label: "Hidden rectangle", input: "1\n9", expectedOutput: "9", hidden: true },
    ],
    hint: "Store width and height on self, then multiply those attributes in area().",
    explanation:
      "The constructor initialises object state. The instance method reads that state through self and returns a result.",
    examinerTip:
      "Use precise OOP vocabulary: class, object, attribute, method, constructor and instance.",
    xpReward: 120,
  },
  {
    id: "al-h-stack",
    title: "Stack Operations",
    description: "Use a Python list to model a LIFO stack.",
    topicId: "al-stack-queue",
    mode: "practice",
    difficulty: "higher",
    qualifications: ["A_LEVEL"],
    examBoards: ["AQA", "OCR"],
    starterCode: `stack = []

stack.append("A")
stack.append("B")
stack.append("C")

# Remove the top item and output it.
# Then output the new top item.

`,
    visibleTests: [
      { id: "stack", label: "LIFO behaviour", input: "", expectedOutput: "C\nB" },
    ],
    hiddenTests: [],
    hint: "list.pop() removes and returns the last item.",
    explanation:
      "A stack is last-in-first-out. After A, B and C are pushed, C is removed first and B becomes the top.",
    examinerTip:
      "Describe an abstract data type by its behaviour, not only by one language-specific implementation.",
    xpReward: 110,
  },
  {
    id: "al-debug-recursion",
    title: "Repair the Recursive Function",
    description: "Fix recursion that moves away from its base case.",
    topicId: "al-recursion",
    mode: "debug",
    difficulty: "higher",
    qualifications: ["A_LEVEL"],
    examBoards: ["AQA", "OCR"],
    starterCode: `def sum_to(n):
    if n == 0:
        return 0
    return n + sum_to(n + 1)

print(sum_to(int(input())))
`,
    stdin: "4",
    visibleTests: [
      { id: "four", label: "sum_to(4)", input: "4", expectedOutput: "10" },
    ],
    hiddenTests: [
      { id: "one", label: "Hidden sum_to(1)", input: "1", expectedOutput: "1", hidden: true },
    ],
    hint: "The recursive argument must move toward zero, not away from it.",
    explanation:
      "The original call uses n + 1, so positive values never reach zero. The recursive step must use n - 1.",
    examinerTip:
      "When debugging recursion, verify both termination and the values returned while calls unwind.",
    xpReward: 120,
  },
];

type ChallengeFilter = {
  qualification: ProgrammingQualification;
  difficulty: ProgrammingDifficulty;
  mode: Exclude<ProgrammingMode, "explore">;
  examBoard?: ProgrammingExamBoard | null;
};

export function getProgrammingChallenges({
  qualification,
  difficulty,
  mode,
  examBoard,
}: ChallengeFilter): ProgrammingChallenge[] {
  return programmingChallenges.filter((challenge) => {
    if (challenge.mode !== mode) return false;
    if (challenge.difficulty !== difficulty) return false;
    if (!challenge.qualifications.includes(qualification)) return false;

    if (
      examBoard &&
      challenge.examBoards &&
      !challenge.examBoards.includes(examBoard)
    ) {
      return false;
    }

    return true;
  });
}
