import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* NAVBAR */}
        <nav className="bg-white shadow p-4 flex justify-between">
          <h1 className="font-semibold text-lg">CS Platform</h1>

          <div className="space-x-4">
            <a href="/">Dashboard</a>
            <a href="/learn">Learn</a>
            <a href="/quiz">Quiz</a>
          </div>
        </nav>

        {/* PAGE CONTENT */}
        {children}
      </body>
    </html>
  );
}
